[[migrating-iptc-7901-to-newsml-g2]]
Migrating IPTC 7901 to NewsML-G2
---------------------------------

[[introduction-13]]
Introduction
~~~~~~~~~~~~

The text transmission standard IPTC 7901 (and ANPA1312, with which it is
closely associated) were a mainstay of the exchange of text for 30
years. The following tables map IPTC 7901 fields to their equivalent in
either NewsML-G2 News Item or News Message.

In some cases there is a choice of field mappings. For example there is
only one timestamp field in IPTC 7901, but several in NewsML-G2.

When providers convert to NewsML-G2, they should determine the source of
the metadata used to populate the IPTC 7901 field. For example, if from
an editorial system, the field label or usage may indicate the NewsML-G2
property to which the 7901 timestamp should be mapped.

Customers converting IPTC 7901 fields to NewsML-G2 properties should
consult their providers’ documentation, or make inquiries about the
mapping of IPTC 7901 fields in the provider’s systems.

[[message-header]]
Message Header
~~~~~~~~~~~~~~

[cols=",,",options="header",]
|=======================================================================
|Field Name |Example |NewsML-G2 Property and Example
|Source Identification |FRS a|
The 7901 definition is "to identify the news service of the originator
and the message." An equivalent NewsML-G2 property would be the
<destination> property of News Message:

<destination>FRS</destination>

An alternative property would be <channel>

<channel>FRS</channel>

Within a News Item, there is a <service> property that may also be used,
however, the IPTC recommends that Source Identification expressed a
distribution intention, not merely a service description. Therefore its
natural home is in News Message.

|Message Number |9999 a|
In IPTC 7901, this may be up to four digits and therefore cannot be
guaranteed to be unique. Some providers reset the counter to zero every
24 hours. The intention is to be able to identify a message within a
sequence of messages.

The equivalent NewsML-G2 field would be <transmitId> of News Message

|Priority of Story |3 a|
IPTC 7901 specifies a single digit of value 1 to 6 inclusive. NewsML-G2
has two equivalents:

<urgency> in the Administrative Metadata group of <contentMeta>

<urgency>3</urgency>

<priority> in the <header> of News Message.

<priority>3</priority>

If the 7901 field is mapped from an editorial system and is under the
control of journalists, then <urgency> would seem to be appropriate,
since this expresses a journalistic intention.

However, some 7901 priority fields may be set by a transmission system
using some other criteria, such as the type of service, and in any case
these values may be linked in order that journalists can move urgent
stories to the head of a priority queue.

|Category of Story |POL a|
In IPTC7901, this could be up to three characters. A provider converting
its categories for NewsML-G2 would create a Controlled Vocabulary
mapping the legacy codes to a Knowledge Item – thus allowing the
receiver to get more information about the code, or to download all of
the codes in order to populate a GUI menu. The CV would be expressed
using <subject> in Content Metadata

<subject type="cpnat:abstract" qcode="cat:POL">

<name>Politics</name>

</subject>

|Word Count |195 a|
The maximum value allowed in IPTC 7901 is 9999. Word Count is one of the
properties of _News Content Characteristics_ group of properties. (The
NewsML-G2 Specification can be downloaded by visiting
http://www.newsml-g2.org/spec[www.newsml-g2.org/spec].) The plain text
of IPTC 7901 is an attribute of the Inline Data component <inlineData>

<inlineData wordcount="195">

Text text text

</inlineData>

There is no limit to the number of words that can be conveyed in
NewsML-G2

|Optional Information |(optional) a|
These two fields are sometimes used by providers in their own specific
format or syntax, so it is not possible to give a definitive mapping
from IPTC 7901 to NewsML-G2.

Providers converting from IPTC 7901 to NewsML-G2 should determine the
source of the information that is being put into the 7901 fields, and
map to the appropriate NewsML-G2 property.

Customers converting an IPTC 5901 service into NewsML-G2 and who are
unsure about which of NewsML-G2’s properties to populate with the 7901
information should consult the provider’s documentation, or inquire of
the provider,

Part of the content of the Keyword/Catch-Line field may be equivalent to
the NewsML-G2 <slugline> property in the Descriptive Metadata group of
<contentMeta>.

<slugline separator="-">US-POLITICS/BUSH</slugline>

|Keyword/Catch-Line | |
|=======================================================================

[[message-text]]
Message Text
~~~~~~~~~~~~

If the message text is to be conveyed as plain text, then the
<inlineData> wrapper would be used. If the migration to NewsML-G2 also
involves migration of the text to some mark-up such as NITF or XHTML,
this would be conveyed in the <inlineXML> wrapper.

[[post-text-information]]
Post-Text Information
~~~~~~~~~~~~~~~~~~~~~

The IPTC7901 post-text fields all relate to date-time. As previously
recommended, providers should examine the origin of the information
being used to fill the IPTC 7901 day and time field, and use the
appropriate NewsML-G2 field for that information. The following are
possibilities:

* If Day and Time is populated by the transmission system, the <sent>
property of News Message would be an appropriate mapping.
* If the IPTC 7901 field represents the only timestamp information
available from the provider’s system, then the provider MUST put this
information in the <versionCreated> timestamp property of <itemMeta>
since its use is a mandatory requirement of NewsML-G2,
* If versioning of Items is being implemented, then the original
timestamp may be preserved in <firstCreated>

These properties are of XML date time type so must express the FULL date
and a time with time zone:

<versionCreated>2009-02-09T12:30:00Z</versionCreated>

If the provider believes that the IPTC 7901 day and time is being
populated from the timestamp on the story itself, then subject to the
rule of <versionCreated> being followed, the appropriate properties
would be <contentCreated> or <contentModified>.in the Management
Metadata group of <contentMeta>.

If versioning is being implemented, the original day and time may be
preserved in <contentCreated>, If <contentModified> is used, then
<contentCreated> SHOULD also be present

Both properties use TruncatedDateTime property type, allowing the value
to be truncated from the right.

<contentCreated>2009-02-09</contentCreated>

[cols=",,",options="header",]
|=======================================================================
|Field Name |Example |NewsML-G2 Property and Example
|Day and Time |091230 |Six digits are be used to express the day and
time in IPTC 7901, in practice this means a format of DDHHMM, where DD
is the day of the month, HH is the hour, MM minutes. In NewsML-G2, there
are more timestamp fields available,

|Time Zone |GMT |Three-alpha character field. Optional in IPTC 7901. No
separate equivalent in NewsML-G2 (none needed)

|Month of Transmission |Feb |Three-alpha character field. Optional in
IPTC 7901. No separate equivalent in NewsML-G2 (none needed)

|Year of Transmission |09 |Two-digit field. Optional in IPTC 7901. No
separate equivalent in NewsML-G2 (none needed)
|=======================================================================

