[[expressing-company-financial-information]]
Expressing company financial information
----------------------------------------

[[background]]
Background
~~~~~~~~~~

Company financial information is a common feature of news distributed by
many news providers; company information is typically indexed in news
using a "ticker symbol", for example:

Apple Inc (NYSE:AAPL) today announced the…

However, this easy and widely-used "shorthand" for indexing company
information has a number of traps for those creating machine-readable
metadata, especially when dealing with global markets and diverse
customer requirements.

Ticker symbols are NOT unambiguous identifiers for companies; they
identify specific financial instruments belonging to companies, usually
tied to specific markets or exchanges. For example, the ticker symbol
for Rio Tinto is "RIO" in London, but "RTP" in New York; similarly
NYSE:AAPL identifies shares of Apple Inc. traded on the New York Stock
Exchange, not the company. Other issues include:

* A company may have many different financial instruments, all
identified by specific ticker symbols.
* A company’s shares may be traded on many different markets; the ticker
symbols may or may not be the same across markets. For example IBM has
the same ticker symbol IBM on the New York, Amsterdam, Frankfurt, London
and Mexico Exchanges; as mentioned above, Rio Tinto has the ticker
symbol RIO in London, but RTP on the New York, Frankfurt and Mexico
exchanges.
* There are many different schemes for labelling financial markets, for
example the London Stock Exchange is variously identified as "LON",
"LSE" and "LN" to give only three examples.

The NewsML-G2 <hasInstrument> structure addresses these issues by
enabling providers to use a globally unique identifier for companies,
and linking each of the company ticker symbols to this identifier, while
giving extensive and unambiguous information about each of the ticker
symbol. It is available at PCL as a child of the Organisation Details
wrapping element <organisationDetails>.

[[hasinstrument-properties-as-attributes]]
<hasInstrument> properties (as attributes)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

[cols=",,,,",options="header",]
|=======================================================================
|Definition |Name |Cardinality |Datatype |Example/Notes
|A symbol for the financial instrument |symbol   |(1) |String
|symbol="RIO" 

|The  source of the financial instrument symbol |symbolsrc |(0..1)
|QCodeType |symbolsrc="symsrc:MDNA"

|A venue in which this financial instrument is traded |market |(0..1)
|QCodeType a|
market="mic:XLON"

The scheme alias "mic" refers to the ISO-supported Market Identification
Code scheme

|The label used for the market |marketlabel |(0..1) |String
|marketlabel="LSE"

|The source of the market label |marketlabelsrc |(0..1) |QCodeType
|marketlabelsrc="mlsrc:MDNA"

|The type(s) of the financial instrument |type |(0..1) |QCodeListType
|type="instrtype:share"

|The rank of the associated financial instrument symbol amongst other
symbols |rank |(0..1) |NonNegativeInteger |rank=1
|=======================================================================

[[examples]]
Examples
^^^^^^^^

At its simplest, a symbol for the financial instrument and a label for
the market on which it is traded may be sufficient:

<hasInstrument

symbol="AAPL"

marketlabel="NYSE" />

It is recommended that the optional @symbolsrc should be used to
identify the authority for the symbol. This will disambiguate similar
symbols that identify different financial instruments.

<hasInstrument

symbol="AAPL"

symbolsrc="symsrc:MDNA"

marketlabel="NYSE" />

Other share identifiers may be used. In this example the ISIN
(International Stock Identification Number) is used, and the authority
for the symbol is identified as the ISO. Note that the CV only
identifies the authority, not the authority’s scheme; which may not be
available to the end user. This example does not give a market label,
but unambiguously identifies the market on which the instrument is
traded using @market and a value from the Market Identification Codes
(an ISO scheme) using the scheme alias "mic".

<hasInstrument

symbol="12345678"

symbolsrc="symsrc:ISO"

market="mic:XLON" />

The @marketlabel enables the provider to denote the market on which the
financial instrument is traded from their own or another’s scheme, and
to identify the scheme using the @marketlabelsrc. For example the
following identifies the Toronto Stock Exchange from Bloomberg’s CV of
market labels:

<hasInstrument

symbol="12345678"

symbolsrc="symsrc:ISO"

marketlabel="####@CN"

marketlabelsrc="_mlsrc:bbg"_ />

Financial instruments are identified on many platforms and it may be
necessary to indicate the preferred symbol amongst a group of symbols
given for a single financial instrument. For example, if the symbols
used on a proprietary news platform (for example Reuters or Bloomberg)
link to further platform functions, the platform provider will wish to
indicate that the use of their symbol is preferred. Rank is used to
indicate this preference; in the following example, only one instrument
has a rank:

<hasInstrument

symbol="RTO.L"

symbolsrc="symsrc:reuters"

marketlabel="LSE"

rank="1" />

<hasInstrument

symbol="12345678"

symbolsrc="symsrc:ISO"

marketlabel="XLON" />

[[adding-hasinstrument-to-a-newsml-g2-item]]
Adding <hasInstrument> to a NewsML-G2 item
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The <hasInstrument> property can be used within a NewsML-G2 News Item in
two ways: by reference in Content Metadata from a <subject> element, or
from the Content itself via <inlineRef>, In both cases, one or more
<hasInstrument> elements are conveyed within an <assert> wrapper
element. For more details on the use of <assert> see The Assert wrapper:
in a nutshell assertions such as these enable supplementary information
about a concept to be carried locally within a NewsML-G2 Item. Into the
<assert> wrapper we can place a further wrapping element
<organisationDetails> which can contain the <hasInstrument> information:

<assert literal="Acme Widget">

<organisationDetails>

<contactInfo>

<phone>+1 (416) 922 5834</phone>

<email>info@acmewidgets.com</email>

</contactInfo>

<hasInstrument

symbol="AWG"

symbolsrc="symsrc:MDNA"

market="mic:XTSE"

marketlabel="TSX"

marketlabelsrc="mlsrc:MDNA"

type="instrtype:share" />

</organisationDetails>

</assert>

The <assert> in this example is identified by a @literal, and is
referenced by the same literal value in a <subject> element:

<contentMeta>

<contentCreated>2011-12-06T07:55:00+00:00</contentCreated>

<subject type="cpnat:organisation" literal="Acme Widget">

<name>Acme Widget Sales Inc</name>

</subject>

<headline>

Acme Widgets announces annual results

</headline>

<description role="ANDescRole:abstract">

Acme Widgets (XTSE:AWG), a leader in the

production of quality metal widgets, announced a six per cent increase
in

profits....

</description>

<language tag="en-US" />

</contentMeta>

Note that either a @qcode or @uri could have been used as the
identifier, instead of @literal.

Many companies may be mentioned in the content of the News Item; it
would be limiting to have to place all of them into <subject> elements.
Using <inlineRef>, the <hasInstrument> elements can be referenced from
the content, but in order to do so, @idrefs must be added to the assert
for each organisation that is referenced in the content:

<assert idrefs="w001" literal="Acme Widget">

<organisationDetails>

<contactInfo>

<phone>+1 (416) 922 5834</phone>

<email>info@acmewidgets.com</email>

</contactInfo>

<hasInstrument

symbol="AWG"

symbolsrc="symsrc:MDNA"

market="mic:XTSE"

marketlabel="TSX"

marketlabelsrc="mlsrc:MDNA"

type="instrtype:share" />

</organisationDetails>

</assert>

The organisation is tagged with the corresponding @id in the content (in
this case as an attribute of the HTML <span> element).


<h1>Acme Widgets announces annual results </h1>

<p>TORONTO (Agencies) – Leading widget manufacturer **<span
id="w001">**Acme Widgets +
(XTSE:AWG)</span> today announced a six per cent jump in quarterly
profits for +
Q3 2016 on the back of heavy demand for its latest widget technology
from +
automotive customers.</p>


1.  _
[[_Ref434903828]]Company Financial Information
_

All Scheme Aliases used in listing below indicate IPTC NewsCodes
vocabularies, except for the following alias values: _ANDescRole,
symsrc, mlsrc, instrtype,_

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<newsItem xmlns="http://iptc.org/std/nar/2006-10-01/"

guid="urn:newsml:acmenews.com:20020408:201003230594296001"

version="2"

standard="NewsML-G2"

standardversion="2.23"

conformance="power"

xml:lang="en-US">

<catalogRef

href="http://www.iptc.org/std/catalog/catalog.IPTC-G2-Standards_29.xml"
/>

<catalogRef

href="http://www.acmenews.com/NewsML/acmenews_NewsML-G2_Catalog_1.xml"
/>

<rightsInfo>

<copyrightHolder uri="http://www.acmenews.com" />

<copyrightNotice>Copyright 2012 - Acme Newswire</copyrightNotice>

<usageTerms>Not for distribution in the United

States</usageTerms>

</rightsInfo>

<itemMeta>

<itemClass qcode="ninat:text" />

<provider uri="http://www.acmenews.com" />

<versionCreated>2016-12-17T08:00:00+00:00</versionCreated>

<firstCreated>2011-12-06T08:00:00+00:00</firstCreated>

<pubStatus qcode="stat:usable" />

</itemMeta>

<contentMeta>

<contentCreated>2011-12-06T07:55:00+00:00</contentCreated>

<subject type="cpnat:organisation" literal="Acme Widget">

<name>Acme Widget Sales Inc</name>

</subject>

<headline>

Acme Widgets profits up

</headline>

<description role="ANDescRole:abstract">

Acme Widgets (XTSE:AWG), a leader in the

production of quality metal widgets, today announced a six per cent
increase in

profits.

</description>

<language tag="en-US" />

</contentMeta>

<assert idrefs="w001" literal="Acme Widget">

<organisationDetails>

<contactInfo>

<phone>+1 (416) 922 5834</phone>

<email>info@acmewidgets.com</email>

</contactInfo>

<hasInstrument

symbol="AWG"

symbolsrc="symsrc:MDNA"

market="mic:XTSE"

marketlabel="TSX"

marketlabelsrc="mlsrc:MDNA"

type="instrtype:share" />

</organisationDetails>

</assert>

<contentSet>

_
<inlineXML contenttype="application/xhtml+xml" xml:lang="en"
...>
_

<html xmlns="http://www.w3.org/1999/xhtml">

<head>...</head>

<body>

<h1>Acme Widgets reveals 6pc profit boost </h1>

<p>TORONTO (Agencies) – Leading widget manufacturer **<span
id="w001">**Acme

Widgets (XTSE:AWG)</span> today announced a six per cent jump in
quarterly

profits for Q3 2016 on the back of heavy demand for its latest widget

technology from automotive customers.</p>

</body>

</html>

</inlineXML>

</contentSet>

</newsItem>

